### ISSUE TITLE
How do?

### ISSUE THREAD

**Issue by Belariean** [TypQxQ/Klipper_ToolChanger#15]
Greetings, 

The fact that some one has gone to the effort of creating a tool changer for those of us with many tool heads, I thank you.

so, just curious if this is a Macro based system or is there a UI menu that I should be looking for?

also, if you have any tool examples, it would help me answer some of those questions

Thanks

**Comment by TypQxQ** [comment]
Hi!
You can find the examples in the config directory.
I save my current config as a backup here: https://github.com/TypQxQ/DuetBackup/tree/main/qTC-Klipper
There is no GUI implementation for this because I haven’t found a way to add custom panels to Mainsail. 
I have planned to add a KlipperScreen UI like the one for ERCF but will have to find the time. 
Happy you like it!
